global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: flask_app_scraping
    metrics_path: /metrics
    static_configs:
      - targets:
        - web-app:5000
        

